import Head from 'next/head';
import Image from 'next/image';
import styled, { createGlobalStyle } from 'styled-components';
import Banner from '../components/Banner';
import Signcard from '../components/Signcard';
import Videobanner from '../components/Videobanner';

const Main = styled.main`
  display: flex;
  background-color: var(--color-one);
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 91vh;
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Main>
        <h1>Main content</h1>
        <p>Pagina para probar NextJs</p>
      </Main>
      <Banner
        title="Banner"
        subtitle="subtitle"
        bgColor="rgba(255, 255, 255, 0.75)"
        color="white"
      />
      <Videobanner>
        <Signcard />
      </Videobanner>
    </div>
  );
}
