import Head from 'next/head';
import Image from 'next/image';
import styled, { createGlobalStyle } from 'styled-components';
import Banner from '../components/Banner';
import Signcard from '../components/Signcard';
import Videobanner from '../components/Videobanner';

const Main = styled.main`
  display: flex;
  //background-color: var(--color-one);
  background-color: rgba(30, 144, 255, 0.82);
  //filter: opacity(0.9);
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 91vh;
  position: relative;
  width: 100%;
  height: 80vh;

  h1,
  p {
    z-index: 1;
  }

  svg {
    position: absolute;
    margin: 12px;
    color: var(--color-four);
    filter: opacity(0.95);
    z-index: 0;
  }
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content="#2E4053" />
      </Head>
      <Videobanner height="85vh">
        <Main>
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="80%"
            height="80%"
            fill="currentColor"
            className="bi bi-cloud-rain-fill"
            viewBox="0 0 16 16"
          >
            <path d="M4.158 12.025a.5.5 0 0 1 .316.633l-.5 1.5a.5.5 0 1 1-.948-.316l.5-1.5a.5.5 0 0 1 .632-.317zm3 0a.5.5 0 0 1 .316.633l-1 3a.5.5 0 1 1-.948-.316l1-3a.5.5 0 0 1 .632-.317zm3 0a.5.5 0 0 1 .316.633l-.5 1.5a.5.5 0 1 1-.948-.316l.5-1.5a.5.5 0 0 1 .632-.317zm3 0a.5.5 0 0 1 .316.633l-1 3a.5.5 0 1 1-.948-.316l1-3a.5.5 0 0 1 .632-.317zm.247-6.998a5.001 5.001 0 0 0-9.499-1.004A3.5 3.5 0 1 0 3.5 11H13a3 3 0 0 0 .405-5.973z" />
          </svg>
          <h1>Lorem, ipsum.</h1>
          <p>Pagina para probar NextJs</p>
        </Main>
      </Videobanner>
      <Banner
        title="Banner"
        subtitle="subtitle"
        bgColor="rgba(255, 255, 255, 0.75)"
        cardColor="var(--color-one)"
        color="white"
        img="https://images.unsplash.com/photo-1527079739242-736e10a5fbb8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2274&q=80"
      />
      <Videobanner height="60vh">
        <Signcard />
      </Videobanner>
      <Banner
        title="Banner"
        subtitle="subtitle"
        bgColor="rgba(255, 255, 255, 0.80)"
        cardColor="var(--color-three)"
        color="white"
        img="https://images.unsplash.com/photo-1527079739242-736e10a5fbb8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2274&q=80"
      />
    </div>
  );
}
